### ISSUE TITLE
adding_groups migration can't find AuthSource

### ISSUE THREAD

**Issue by daveshenk** [stakach/em_control#3]
--trace reveals a problem around lines 37-42 of 

uninitialized constant AddingGroups::AuthSource

If I comment out those lines, I can run the migrations, and get myself a login prompt.

**Comment by stakach** [comment]
That's caused by the issue with Rails Admin. Although as your database is unpopulated those lines were not needed.

Assuming you used bundler you have to goto: ruby/lib/ruby/gems/1.9.1/bundler/gems/rails_admin-xxxx/lib/tasks/rails_admin.rake and comment out the first line that overwrites the environment task.

You'll need to do that to actually run the control system.

**Comment by daveshenk** [comment]
Commented out

task :environment => :disable_rails_admin_initializer

Is there a default username and password? Or a method to create a new one? All I'm seeing is a login prompt with a change password link that tells me I'm using an invalid user or password

**Comment by stakach** [comment]
Writing a seed for you now.
There is one there already, however it connects to our internal LDAP lol.

Won't be a min.

**Comment by stakach** [comment]
Ok seed available now

**Comment by stakach** [comment]
Ok, added a new wiki entry: https://github.com/stakach/em_control/wiki/Defining-a-new-system

**Comment by daveshenk** [comment]
Excellent, thanks. Interface is up and running, and I'm starting to set it up following the latest wiki entry.
