### ISSUE TITLE
rake control has uninitialized constant Control::ControlSystem

### ISSUE THREAD

**Issue by daveshenk** [stakach/em_control#5]
It seems that both control/core/system.rb and control/interfaces/communicator.rb reference each other. 

I've been playing around with load order in em-control.rb, but it seems that no matter which get's loaded first, one can't find the other. 

On a side note, I'm on the market for an hdmi matrix (connected to a couple of rooms via cat6), I don't need a ton of HDMI sources, have any recommendations?

**Comment by stakach** [comment]
http://www.kramerelectronics.com/ is pretty good value
However I believe http://www.extron.com/ is better quality

Both have a variety of switch types and sizes.

The issue is caused by rails admin overwriting the environment task.
It's something like ruby/lib/gems/1.9.1/bundler/rails_admin#{latest commit}/lib/tasks/rails_admin.rake (off the top of my head) and you'll need to comment out the first line.

I've raised it before however I didn't understand the response so just left it sferik/rails_admin#850

**Comment by daveshenk** [comment]
The app seems to be working after commenting out that line, now I just need to write a device module. 

I can already feel my wallet getting lighter looking at the Extron site. Maybe it's a good thing they don't show pricing or a dealer locator.
